=== Oowekyala/pmd/pmd-core/src/main/resources/ruleset_700.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="https://pmd-code.org/ruleset/7.0.0"
           targetNamespace="https://pmd-code.org/ruleset/7.0.0"
           elementFormDefault="qualified">

    <!-- This is the main document for the schema -->
    <!-- This draft version converts most attributes to nested elements -->

    <!-- TODO use xsd:documentation and xsd:annotation to document the schema -->


    <xs:include schemaLocation="ruleset_700_preamble.xsd"/>
    <xs:include schemaLocation="ruleset_700_properties.xsd"/>

    <!-- Type allowing only valid values for a language name -->

    <xs:element name="ruleset">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="description" type="xs:string"/>
                <xs:element name="exclude-pattern" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="include-pattern" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <!-- Rule definitions and imports. This XSD allows an empty ruleset to be defined -->
                <xs:choice maxOccurs="unbounded">
                    <xs:element ref="rule-def" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element name="rule-import" type="rule-import" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element name="ruleset-import" type="ruleset-import" minOccurs="0" maxOccurs="unbounded"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="ruleNamesMustBeUnique">
            <xs:selector xpath="rule-def"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>

    <xs:group name="optional-rule-elts">
        <xs:sequence>
            <xs:element name="since" type="xs:string" minOccurs="0"/>
            <xs:element name="deprecated" type="deprecation-info" minOccurs="0"/>
            <xs:element name="priority" type="priority" minOccurs="0" default="medium"/>
            <xs:element name="suppressions" minOccurs="0">
                <xs:complexType>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element name="regex" type="xs:string"/>
                        <xs:element name="xpath" type="simple-xpath"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:group>

    <xs:complexType name="deprecation-info">
        <xs:sequence>
            <xs:element name="since" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <!-- An empty list is also allowed -->
    <xs:complexType name="examples">
        <xs:sequence>
            <xs:element name="example" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="rule-def">
        <xs:complexType>
            <xs:sequence>
                <!-- Required               -->
                <xs:element name="message" type="xs:string"/>
                <xs:element name="description" type="xs:string"/>
                <xs:group ref="optional-rule-elts"/>
                <xs:element ref="impl"/>
                <xs:element name="properties" type="property-overrides" minOccurs="0"/>
                <xs:element name="examples" type="examples" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="name" type="rule-name"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="impl">
        <xs:annotation>
            <xs:documentation>
                This is the implementation section of the rule. Things defined here
                cannot be overridden by a client of the rule.

                You must define a language (possibly with a specific version range),
                and select either a Java class that implements the rule behavior,
                or write an XPath rule in the XML.

                XPath rules can declare properties in the XML, while Java rules do so
                directly in Java.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="language">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="minVersion" type="version-id" minOccurs="0"/>
                            <xs:element name="maxVersion" type="version-id" minOccurs="0"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="language-id" use="required"/>
                    </xs:complexType>
                </xs:element>

                <xs:choice>
                    <xs:element name="xpath">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="version" type="xpath-version-id" minOccurs="0" maxOccurs="0"/>
                                <xs:element name="expr" type="xs:string"/>
                                <xs:element name="property-defs" type="property-defs" minOccurs="0"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="class" type="class-qualified-name"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="simple-xpath">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="version" type="xpath-version-id"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- Imports a whole ruleset -->
    <xs:complexType name="ruleset-import">
        <!-- Must be a reference to a ruleset/category -->
        <xs:sequence>
            <xs:element name="exclude-rule" type="rule-name" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="ref" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- References a *single* rule. -->
    <xs:complexType name="rule-import">
        <xs:sequence>
            <xs:element name="name" type="xs:string" minOccurs="0"/>
            <xs:element name="message" type="xs:string" minOccurs="0"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:group ref="optional-rule-elts"/>
            <xs:element name="properties" type="property-overrides" minOccurs="0"/>
            <xs:element name="examples" type="examples" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="ref" type="rule-reference" use="required"/>
    </xs:complexType>


</xs:schema>

=== Oowekyala/pmd/pmd-core/src/main/resources/ruleset_700_test_out.xml
<?xml version="1.0" encoding="UTF-8"?>
<ruleset xmlns="http://pmd.sourceforge.net/ruleset/7.0.0"
         xmlns:ns0="http://www.w3.org/2001/XMLSchema-instance"
         ns0:schemaLocation="http://pmd.sourceforge.net/ruleset/7.0.0 file:///home/clifrr/Documents/Git/pmd/pmd-core/src/main/resources/ruleset_700.xsd">
   <name>Code Style</name>

    <description>
        Rules which enforce a specific coding style.
    </description>

   <!-- Some comment? -->

    <rule-def>
      <name>AtLeastOneConstructor</name>
      <message>Each class should declare at least one constructor</message>
      <description>

            Each non-static class should declare at least one constructor.
            Classes with solely static members are ignored, refer to [UseUtilityClassRule](pmd_rules_java_design.html#useutilityclass) to detect those.
            
        </description>
      <since>1.04</since>
      <impl>
         <language id="java"/>
         <class>net.sourceforge.pmd.lang.java.rule.codestyle.AtLeastOneConstructorRule</class>
      </impl>
      <examples>
         <example>
            
public class Foo {
   // missing constructor
  public void doSomething() { ... }
  public void doOtherThing { ... }
}

        </example>
      </examples>
   </rule-def>

    <rule-def>
      <name>AvoidDollarSigns</name>
      <message>Avoid using dollar signs in variable/method/class/interface names</message>
      <description>
            Avoid using dollar signs in variable/method/class/interface names.
        </description>
      <since>1.5</since>
      <impl>
         <language id="java"/>
         <class>net.sourceforge.pmd.lang.java.rule.codestyle.AvoidDollarSignsRule</class>
      </impl>
      <examples>
         <example>
            
public class Fo$o {  // not a recommended name
}

        </example>
      </examples>
   </rule-def>

    <rule-def>
      <name>UseShortArrayInitializer</name>
      <message>Array initialization can be written shorter</message>
      <description>

            When declaring and initializing array fields or variables, it is not necessary to explicitly create a new array
            using `new`. Instead one can simply define the initial content of the array as a expression in curly braces.

            E.g. `int[] x = new int[] { 1, 2, 3 };` can be written as `int[] x = { 1, 2, 3 };`.
            
        </description>
      <since>6.15.0</since>
      <impl>
         <language id="java"/>
         <xpath>
            <expr>
//VariableDeclarator
    [VariableDeclaratorId[@ArrayType = true() and @TypeInferred = false()]]
    [VariableInitializer/Expression/PrimaryExpression/PrimaryPrefix/AllocationExpression/ArrayDimsAndInits/ArrayInitializer]
                </expr>
         </xpath>
      </impl>
      <examples>
         <example>
            
Foo[] x = new Foo[] { ... }; // Overly verbose
Foo[] x = { ... }; //Equivalent to above line

        </example>
      </examples>
   </rule-def>
</ruleset>

=== Oowekyala/pmd/pmd-core/src/main/resources/ruleset-7-sample.xml
<ruleset xmlns="http://pmd.sourceforge.net/ruleset/7.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/7.0.0 ruleset_700.xsd">
    <name>My ruleset</name>
    <description>smsms</description>

    <rule-def language="java">
        <name>MyRule</name>
        <message>Some message</message>
        <description>TODO</description>
        <impl>
            <class>Foo</class>
        </impl>
        <properties>
            <property name="foo">
                <none/>
            </property>
        </properties>
    </rule-def>


    <rule-def language="java">
        <name>AtLeastOneConstructor</name>
        <message>Each class should declare at least one constructor</message>
        <description>
            Each non-static class should declare at least one constructor.
            Classes with solely static members are ignored, refer to [UseUtilityClassRule](pmd_rules_java_design.html#useutilityclass) to detect those.
        </description>
        <since>1.04</since>
        <priority>medium</priority>
        <impl>
            <class>net.sourceforge.pmd.lang.java.rule.codestyle.AtLeastOneConstructorRule</class>
        </impl>
        <examples>
            <example>
public class Foo {
   // missing constructor
  public void doSomething() { ... }
  public void doOtherThing { ... }
}
            </example>
        </examples>
    </rule-def>

    <rule-def language="java">
        <name>AnXPathRule</name>
        <message>Some message</message>
        <description>TODO</description>
        <impl>
            <class>Foo</class>
        </impl>
        <properties>
            <property name="foo">
                <none/>
            </property>
            <property name="foo">
                <none/>
            </property>
        </properties>
    </rule-def>

</ruleset>
